#!/usr/bin/env python3
"""
NEXUS REST API Gateway
======================
Wraps all 44 MCP tools as standard REST POST endpoints.
Enables access from ChatGPT Custom GPTs, Gemini CLI, Cursor, Continue.dev,
Windsurf, Vibe CLI, and any HTTP client.

Architecture:
  POST /api/v1/tools/{tool_name}   — call any tool
  GET  /api/v1/tools               — list all tools with schemas
  GET  /openapi.json               — OpenAPI 3.1 spec (for ChatGPT Actions)
  GET  /health                     — health check
  GET  /docs                       — Swagger UI (auto-generated by FastAPI)
  GET  /redoc                      — ReDoc UI

Auth: Bearer token via NEXUS_AUTH_TOKEN env var (same as MCP).
"""

from __future__ import annotations

import asyncio
import inspect
import json
import logging
import os
import time
from typing import Any, Optional

from fastapi import Depends, FastAPI, HTTPException, Request, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.openapi.utils import get_openapi
from fastapi.responses import JSONResponse
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from pydantic import BaseModel, Field

log = logging.getLogger("nexus-rest")

# ── Auth ─────────────────────────────────────────────────────────────────────

_bearer_scheme = HTTPBearer(auto_error=False)


def _get_auth_token() -> str:
    """Read auth token from env at call time (supports hot-reload)."""
    return os.getenv("NEXUS_AUTH_TOKEN", "")


async def require_auth(
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(_bearer_scheme),
) -> str:
    """Dependency: validate Bearer token. Raises 401/403 on failure."""
    expected = _get_auth_token()

    if not expected:
        # Auth token not configured — reject all protected requests.
        # Returns 503 (not 500) to avoid leaking misconfiguration info.
        # Log at error level so operators notice immediately.
        log.error("NEXUS_AUTH_TOKEN not configured — rejecting protected request")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Service not available.",
        )

    if not credentials:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Missing Authorization header. Use: Authorization: Bearer <token>",
            headers={"WWW-Authenticate": "Bearer"},
        )

    if credentials.credentials != expected:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Invalid Bearer token.",
        )

    return credentials.credentials


# ── Tool Registry ─────────────────────────────────────────────────────────────

class ToolDefinition(BaseModel):
    """Metadata for a registered MCP tool exposed via REST."""
    name: str
    title: str
    description: str
    input_schema: dict
    annotations: dict = Field(default_factory=dict)


# Global registry: tool_name → (callable, input_model_class)
_TOOL_REGISTRY: dict[str, tuple[Any, Any]] = {}
_TOOL_DEFS: dict[str, ToolDefinition] = {}


def _extract_json_schema(model_class: Any) -> dict:
    """Extract JSON Schema from a Pydantic BaseModel class."""
    if model_class is None:
        return {"type": "object", "properties": {}}
    try:
        if hasattr(model_class, "model_json_schema"):
            schema = model_class.model_json_schema()
            # Remove Pydantic internal keys not needed in OpenAPI
            schema.pop("title", None)
            return schema
    except Exception:
        pass
    return {"type": "object", "properties": {}}


def _get_input_model(func: Any) -> Any:
    """Extract the first non-Context parameter type from a tool function."""
    try:
        sig = inspect.signature(func)
        for param_name, param in sig.parameters.items():
            if param_name in ("self", "ctx", "context"):
                continue
            annotation = param.annotation
            if annotation is inspect.Parameter.empty:
                continue
            # Check if it's a Pydantic model
            if hasattr(annotation, "model_json_schema") or hasattr(annotation, "__fields__"):
                return annotation
    except Exception:
        pass
    return None


def register_tool_for_rest(
    name: str,
    func: Any,
    title: str = "",
    description: str = "",
    annotations: dict = None,
) -> None:
    """Register a tool function in the REST gateway registry."""
    input_model = _get_input_model(func)
    schema = _extract_json_schema(input_model)

    _TOOL_REGISTRY[name] = (func, input_model)
    _TOOL_DEFS[name] = ToolDefinition(
        name=name,
        title=title or name,
        description=description or (func.__doc__ or "").strip(),
        input_schema=schema,
        annotations=annotations or {},
    )
    log.debug(f"REST gateway: registered tool '{name}'")


def discover_tools_from_mcp(mcp_instance: Any) -> None:
    """
    Auto-discover all tools registered on a FastMCP instance and
    register them in the REST gateway.

    FastMCP stores tools in _tool_manager._tools (dict[str, Tool]).
    Each Tool has: .name, .fn, .description, .annotations.
    """
    try:
        # FastMCP 2.x / mcp 1.9+: tools live in _tool_manager
        tool_manager = getattr(mcp_instance, "_tool_manager", None)
        if tool_manager is None:
            # Older FastMCP: try direct _tools attribute
            tool_manager = mcp_instance

        tools_dict = getattr(tool_manager, "_tools", {})
        if not tools_dict:
            # Some versions use 'tools' property
            tools_dict = getattr(tool_manager, "tools", {})

        if not tools_dict:
            log.warning("Could not discover tools from FastMCP instance — _tools is empty")
            return

        for tool_name, tool_obj in tools_dict.items():
            fn = getattr(tool_obj, "fn", None)
            if fn is None:
                fn = getattr(tool_obj, "func", None)
            if fn is None:
                log.warning(f"Tool '{tool_name}' has no callable fn — skipping")
                continue

            title = ""
            ann = {}
            raw_ann = getattr(tool_obj, "annotations", None)
            if raw_ann:
                if hasattr(raw_ann, "title"):
                    title = raw_ann.title or ""
                    ann = {
                        "readOnlyHint": getattr(raw_ann, "readOnlyHint", False),
                        "destructiveHint": getattr(raw_ann, "destructiveHint", False),
                        "idempotentHint": getattr(raw_ann, "idempotentHint", False),
                        "openWorldHint": getattr(raw_ann, "openWorldHint", False),
                    }
                elif isinstance(raw_ann, dict):
                    title = raw_ann.get("title", "")
                    ann = raw_ann

            description = getattr(tool_obj, "description", "") or (fn.__doc__ or "").strip()

            register_tool_for_rest(
                name=tool_name,
                func=fn,
                title=title,
                description=description,
                annotations=ann,
            )

        log.info(f"REST gateway: discovered {len(_TOOL_REGISTRY)} tools from FastMCP")

    except Exception as e:
        log.error(f"Tool discovery failed: {e}", exc_info=True)


# ── Response Models ───────────────────────────────────────────────────────────

class ToolCallResponse(BaseModel):
    """Standard response wrapper for all tool calls."""
    tool: str
    success: bool
    result: Any
    error: Optional[str] = None
    duration_ms: float


class ToolListItem(BaseModel):
    name: str
    title: str
    description: str
    input_schema: dict
    annotations: dict


class ToolListResponse(BaseModel):
    count: int
    tools: list[ToolListItem]


class HealthResponse(BaseModel):
    status: str
    tools_registered: int
    version: str
    timestamp: float


class ToolsCallRequest(BaseModel):
    """CodeAct /tools/call request body — module-level for FastAPI body detection."""
    name: str
    arguments: dict = Field(default_factory=dict)


# ── FastAPI App ───────────────────────────────────────────────────────────────

def create_rest_app() -> FastAPI:
    """
    Create and configure the FastAPI REST gateway application.
    Call discover_tools_from_mcp() after creating the app to populate the registry.
    """

    app = FastAPI(
        title="NEXUS MCP REST Gateway",
        description=(
            "REST API gateway for NEXUS MCP Server. Wraps all 44 MCP tools as standard "
            "HTTP POST endpoints. Compatible with ChatGPT Custom GPT Actions, Gemini CLI, "
            "Cursor, Continue.dev, Windsurf, Vibe CLI, and any HTTP client.\n\n"
            "**Authentication:** All endpoints require `Authorization: Bearer <token>` header.\n\n"
            "**Base URL:** `http://localhost:8080`\n\n"
            "**MCP endpoint:** `http://localhost:8080/mcp`"
        ),
        version="1.0.0",
        docs_url="/docs",
        redoc_url="/redoc",
        openapi_url="/openapi.json",
        contact={
            "name": "gangus-coder",
            "url": "https://github.com/wojciechkowalczyk11to-tech/gangus-coder",
        },
        license_info={
            "name": "MIT",
        },
    )

    # ── CORS ─────────────────────────────────────────────
    app.add_middleware(
        CORSMiddleware,
        allow_origins=["*"],
        allow_credentials=True,
        allow_methods=["GET", "POST", "OPTIONS"],
        allow_headers=["*"],
    )

    # ── Health Check ──────────────────────────────────────

    @app.get(
        "/health",
        response_model=HealthResponse,
        tags=["System"],
        summary="Health check",
        description="Returns server health status and number of registered tools.",
    )
    async def health_check() -> HealthResponse:
        return HealthResponse(
            status="ok",
            tools_registered=len(_TOOL_REGISTRY),
            version="1.0.0",
            timestamp=time.time(),
        )

    # ── List Tools ────────────────────────────────────────

    @app.get(
        "/api/v1/tools",
        response_model=ToolListResponse,
        tags=["Tools"],
        summary="List all available tools",
        description=(
            "Returns all registered MCP tools with their names, descriptions, "
            "and input JSON schemas. Use this to discover what tools are available "
            "and what parameters each tool accepts."
        ),
    )
    async def list_tools(
        _token: str = Depends(require_auth),
    ) -> ToolListResponse:
        items = [
            ToolListItem(
                name=d.name,
                title=d.title,
                description=d.description,
                input_schema=d.input_schema,
                annotations=d.annotations,
            )
            for d in sorted(_TOOL_DEFS.values(), key=lambda x: x.name)
        ]
        return ToolListResponse(count=len(items), tools=items)

    # ── Get Single Tool Schema ────────────────────────────

    @app.get(
        "/api/v1/tools/{tool_name}",
        response_model=ToolListItem,
        tags=["Tools"],
        summary="Get tool schema",
        description="Returns the schema and description for a single tool by name.",
    )
    async def get_tool_schema(
        tool_name: str,
        _token: str = Depends(require_auth),
    ) -> ToolListItem:
        if tool_name not in _TOOL_DEFS:
            raise HTTPException(
                status_code=404,
                detail=f"Tool '{tool_name}' not found. GET /api/v1/tools for full list.",
            )
        d = _TOOL_DEFS[tool_name]
        return ToolListItem(
            name=d.name,
            title=d.title,
            description=d.description,
            input_schema=d.input_schema,
            annotations=d.annotations,
        )

    # ── Call Tool ─────────────────────────────────────────

    @app.post(
        "/api/v1/tools/{tool_name}",
        response_model=ToolCallResponse,
        tags=["Tools"],
        summary="Call a tool",
        description=(
            "Execute any registered MCP tool by name. "
            "The request body must match the tool's input schema "
            "(see GET /api/v1/tools/{tool_name} for schema). "
            "Returns the tool's output wrapped in a standard response envelope."
        ),
        responses={
            200: {"description": "Tool executed successfully"},
            400: {"description": "Invalid input parameters"},
            401: {"description": "Missing or invalid Bearer token"},
            404: {"description": "Tool not found"},
            500: {"description": "Tool execution error"},
        },
    )
    async def call_tool(
        tool_name: str,
        request: Request,
        _token: str = Depends(require_auth),
    ) -> ToolCallResponse:
        if tool_name not in _TOOL_REGISTRY:
            raise HTTPException(
                status_code=404,
                detail=f"Tool '{tool_name}' not found. GET /api/v1/tools for full list.",
            )

        fn, input_model_class = _TOOL_REGISTRY[tool_name]
        start_time = time.monotonic()

        # Parse request body
        try:
            body_bytes = await request.body()
            if body_bytes:
                body_dict = json.loads(body_bytes)
            else:
                body_dict = {}
        except json.JSONDecodeError as e:
            raise HTTPException(
                status_code=400,
                detail=f"Invalid JSON body: {e}",
            )

        # Validate and construct input model
        params_obj = None
        if input_model_class is not None:
            try:
                params_obj = input_model_class(**body_dict)
            except Exception as e:
                raise HTTPException(
                    status_code=400,
                    detail=f"Input validation error: {e}",
                )
        else:
            # Tool accepts raw dict (e.g. manus_delegate)
            params_obj = body_dict

        # Build a minimal Context stub — REST calls don't have MCP session context
        ctx = _RestContext(tool_name=tool_name)

        # Call the tool
        try:
            # Inspect signature to determine how to call
            sig = inspect.signature(fn)
            param_names = list(sig.parameters.keys())

            if len(param_names) == 0:
                result = await fn()
            elif len(param_names) == 1:
                result = await fn(params_obj)
            else:
                # Standard pattern: fn(params, ctx)
                result = await fn(params_obj, ctx)

            duration_ms = (time.monotonic() - start_time) * 1000

            # Normalise result to JSON-serialisable form
            if isinstance(result, str):
                result_payload = result
            elif isinstance(result, (dict, list)):
                result_payload = result
            elif hasattr(result, "model_dump"):
                result_payload = result.model_dump()
            else:
                result_payload = str(result)

            return ToolCallResponse(
                tool=tool_name,
                success=True,
                result=result_payload,
                duration_ms=round(duration_ms, 2),
            )

        except HTTPException:
            raise
        except Exception as e:
            duration_ms = (time.monotonic() - start_time) * 1000
            log.error(f"Tool '{tool_name}' execution error: {e}", exc_info=True)
            return ToolCallResponse(
                tool=tool_name,
                success=False,
                result=None,
                error=str(e),
                duration_ms=round(duration_ms, 2),
            )

    # ── /tools/call — CodeAct contract endpoint ──────────
    # Rust codeact calls POST {NEXUS_URL}/tools/call with {"name": "...", "arguments": {...}}
    # This endpoint bridges that contract to /api/v1/tools/{tool_name}.

    @app.post(
        "/tools/call",
        response_model=ToolCallResponse,
        tags=["Tools"],
        summary="CodeAct tool invocation endpoint",
        description=(
            "Rust CodeAct contract: POST /tools/call {\"name\": \"tool_name\", \"arguments\": {...}}. "
            "Dispatches to the matching registered tool. "
            "Same auth and error semantics as /api/v1/tools/{tool_name}."
        ),
    )
    async def tools_call(
        body: ToolsCallRequest,
        _token: str = Depends(require_auth),
    ) -> ToolCallResponse:
        tool_name = body.name
        if tool_name not in _TOOL_REGISTRY:
            raise HTTPException(
                status_code=404,
                detail=f"Tool '{tool_name}' not found. GET /api/v1/tools for full list.",
            )
        fn, input_model_class = _TOOL_REGISTRY[tool_name]
        start_time = time.monotonic()
        ctx = _RestContext(tool_name=tool_name)
        params_obj = input_model_class(**body.arguments) if input_model_class else body.arguments
        try:
            sig = inspect.signature(fn)
            param_names = list(sig.parameters.keys())
            if len(param_names) == 0:
                result = await fn()
            elif len(param_names) == 1:
                result = await fn(params_obj)
            else:
                result = await fn(params_obj, ctx)
            duration_ms = (time.monotonic() - start_time) * 1000
            result_payload = result if isinstance(result, (str, dict, list)) else (
                result.model_dump() if hasattr(result, "model_dump") else str(result)
            )
            return ToolCallResponse(tool=tool_name, success=True, result=result_payload,
                                    duration_ms=round(duration_ms, 2))
        except HTTPException:
            raise
        except Exception as e:
            duration_ms = (time.monotonic() - start_time) * 1000
            log.error(f"/tools/call '{tool_name}' error: {e}", exc_info=True)
            return ToolCallResponse(tool=tool_name, success=False, result=None,
                                    error=str(e), duration_ms=round(duration_ms, 2))

    # ── Custom OpenAPI 3.1 spec ───────────────────────────
    # FastAPI generates OpenAPI 3.0 by default. We override to produce
    # a richer 3.1-compatible spec with per-tool request body schemas.

    def custom_openapi() -> dict:
        if app.openapi_schema:
            return app.openapi_schema

        # Start with FastAPI's generated spec
        openapi_schema = get_openapi(
            title=app.title,
            version=app.version,
            description=app.description,
            routes=app.routes,
            contact=app.contact,
            license_info=app.license_info,
        )

        # Inject per-tool paths with full request body schemas
        tool_paths: dict = {}
        for tool_name, tool_def in sorted(_TOOL_DEFS.items()):
            path = f"/api/v1/tools/{tool_name}"
            tool_paths[path] = {
                "post": {
                    "operationId": f"call_{tool_name}",
                    "summary": tool_def.title or tool_name,
                    "description": tool_def.description,
                    "tags": ["Tools"],
                    "security": [{"BearerAuth": []}],
                    "requestBody": {
                        "required": True,
                        "content": {
                            "application/json": {
                                "schema": tool_def.input_schema,
                            }
                        },
                    },
                    "responses": {
                        "200": {
                            "description": "Tool executed successfully",
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "type": "object",
                                        "properties": {
                                            "tool": {"type": "string"},
                                            "success": {"type": "boolean"},
                                            "result": {},
                                            "error": {"type": "string", "nullable": True},
                                            "duration_ms": {"type": "number"},
                                        },
                                    }
                                }
                            },
                        },
                        "400": {"description": "Invalid input"},
                        "401": {"description": "Unauthorized"},
                        "404": {"description": "Tool not found"},
                        "500": {"description": "Execution error"},
                    },
                }
            }

        # Merge tool paths into the schema
        openapi_schema.setdefault("paths", {}).update(tool_paths)

        # Add security scheme
        openapi_schema.setdefault("components", {}).setdefault("securitySchemes", {})
        openapi_schema["components"]["securitySchemes"]["BearerAuth"] = {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "Token",
            "description": "NEXUS Auth Token (same as MCP Bearer token)",
        }

        # Add global security requirement
        openapi_schema["security"] = [{"BearerAuth": []}]

        # Upgrade to OpenAPI 3.1.0
        openapi_schema["openapi"] = "3.1.0"

        app.openapi_schema = openapi_schema
        return app.openapi_schema

    app.openapi = custom_openapi  # type: ignore[method-assign]

    return app


# ── Minimal Context Stub ──────────────────────────────────────────────────────

class _RestContext:
    """
    Minimal stub replacing FastMCP's Context for REST calls.
    Tools that use ctx.info(), ctx.warning() etc. will work without errors.
    Tools that use ctx.lifespan_state will get an empty dict (clients are
    accessed via get_clients() singleton, so this is fine).
    """

    def __init__(self, tool_name: str = ""):
        self.tool_name = tool_name
        self.lifespan_state: dict = {}
        self._log = logging.getLogger(f"nexus-rest.ctx.{tool_name}")

    async def info(self, message: str, **kwargs: Any) -> None:
        self._log.info(message)

    async def warning(self, message: str, **kwargs: Any) -> None:
        self._log.warning(message)

    async def error(self, message: str, **kwargs: Any) -> None:
        self._log.error(message)

    async def debug(self, message: str, **kwargs: Any) -> None:
        self._log.debug(message)

    async def report_progress(self, progress: float, total: float = 1.0, **kwargs: Any) -> None:
        self._log.debug(f"Progress: {progress}/{total}")

    # FastMCP Context also has request_context — stub it
    @property
    def request_context(self) -> Any:
        return _RequestContextStub()


class _RequestContextStub:
    """Stub for FastMCP's request_context."""
    lifespan_context: dict = {}
    meta: Any = None
    session: Any = None


# ── Standalone entry point (for testing) ─────────────────────────────────────

if __name__ == "__main__":
    import uvicorn

    # When run standalone, import and discover tools from server.py
    import sys
    sys.path.insert(0, os.path.dirname(__file__))

    from server import mcp as nexus_mcp  # noqa: E402

    rest_app = create_rest_app()
    discover_tools_from_mcp(nexus_mcp)

    log.info(f"Standalone REST gateway: {len(_TOOL_REGISTRY)} tools registered")
    uvicorn.run(rest_app, host="0.0.0.0", port=8081)
